name: Upload Concrete Artifacts

on:
  pull_request:
    types: [closed]
    branches:
      - release/managed-solution-main

concurrency:
  group: ${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  upload-concrete-artifacts:
    name: Upload Concrete Artifacts
    runs-on: [self-hosted, linux, X64, onboarding]
    env:
      ARTIFACT_NAME: dota-server
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.COMMIT_ACCESS_TOKEN}}

      - name: Set up NVM
        run: |
          curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.3/install.sh | bash
          export NVM_DIR="$HOME/.nvm"
          [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
          [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"
          nvm -v
          nvm install 20.0.0
          nvm use 20.0.0
          node -v

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: '20.0.0'

      - name: Upload artifacts
        id: upload-artifacts
        uses: dream11/d11-github-actions/upload-artifacts@vipulmalgotra-patch-1
        with:
            github_token: ${{ secrets.COMMIT_ACCESS_TOKEN}}
            jfrog_username: ${{ secrets.JFROG_USERNAME}}
            jfrog_password: ${{ secrets.JFROG_PASSWORD}}